/*
	https://leetcode.com/problems/find-the-difference/

	You are given two strings s and t.

	String t is generated by random shuffling string s and then add one more letter
	at a random position.

	Return the letter that was added to t.
*/

package solutions

func findTheDifference(s, t string) byte {
	m := make(map[rune]int)
	for _, ch := range s {
		m[ch]++
	}

	for _, ch := range t {
		m[ch]--
	}

	for k, v := range m {
		if v == -1 {
			return byte(k)
		}
	}

	return byte(0)
}
